project:
  type: website
  output-dir: _site
  pre-render: pre-render.R

profile:
  default: student

website:
  title: "EDEP 625 Structural Equation Modeling"
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: index.qmd#lectures
        text: Lectures
      - href: index.qmd#labs
        text: Labs
      - href: index.qmd#assignments
        text: Assignments

format:
  html:
    theme: cosmo
    toc: true
    code-tools: true
